//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Api.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Warehouse.Api.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping item validation failed..
        /// </summary>
        internal static string ShoppingItemProvider_BadRequestException {
            get {
                return ResourceManager.GetString("ShoppingItemProvider_BadRequestException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping item already exists..
        /// </summary>
        internal static string ShoppingItemProvider_ConflictException {
            get {
                return ResourceManager.GetString("ShoppingItemProvider_ConflictException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping item not found..
        /// </summary>
        internal static string ShoppingItemProvider_NotFoundException {
            get {
                return ResourceManager.GetString("ShoppingItemProvider_NotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock item validation failed..
        /// </summary>
        internal static string StockItemProvider_BadRequestException {
            get {
                return ResourceManager.GetString("StockItemProvider_BadRequestException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock item already exists..
        /// </summary>
        internal static string StockItemProvider_ConflictException {
            get {
                return ResourceManager.GetString("StockItemProvider_ConflictException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock item not found..
        /// </summary>
        internal static string StockItemProvider_NotFoundException {
            get {
                return ResourceManager.GetString("StockItemProvider_NotFoundException", resourceCulture);
            }
        }
    }
}
