const enum Validation {
  DISPLAY_NAME_MAX_LENGTH = 100,
  DISPLAY_NAME_MIN_LENGTH = 8,
  PASSWORD_MAX_LENGTH = 100,
  PASSWORD_MIN_LENGTH = 8,
  USERNAME_MAX_LENGTH = 100,
  USERNAME_MIN_LENGTH = 2,
};

export default Validation;
